replicaCount: 1
image:
  repository: registry.digitalocean.com/sku4/repository
  pullPolicy: IfNotPresent
  tag: "grafana-96a1b63"

imagePullSecrets:
  - name: regcred
nameOverride: "grafana"
fullnameOverride: "grafana"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels:
  app: grafana

podSecurityContext: {}
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  create: true
  type: ClusterIP
  externalPort: 3000
  internalPort: 3000

ingress:
  enabled: false

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

#livenessProbe:
#  httpGet:
#    path: /
#    port: http
#readinessProbe:
#  httpGet:
#    path: /
#    port: http

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  type: RollingUpdate

volumes:
  - name: grafana-storage
    persistentVolumeClaim:
      claimName: grafana

volumeMounts:
  - name: grafana-storage
    mountPath: /var/lib/grafana
    subPath: grafana

env:
  - name: GF_SERVER_DOMAIN
    valueFrom:
      secretKeyRef:
        name: ad-app
        key: gf_server_domain

nodeSelector: {}

tolerations: []

affinity: {}

persistentVolume:
  path: /mnt/metrics
  nodeAffinity:
    hostname:
      - multitest
  storage: 300Mi

storageClass:
  create: true
  name: grafana
