replicaCount: 1
image:
  repository: skubach/skubach
  pullPolicy: IfNotPresent
  tag: "e227f19c0044"

imagePullSecrets:
  - name: regcred
nameOverride: "prometheus"
fullnameOverride: "prometheus"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels:
  app: prometheus

podSecurityContext: {}
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  create: true
  type: ClusterIP
  externalPort: 9090
  internalPort: 9090

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

#livenessProbe:
#  httpGet:
#    path: /
#    port: http
#readinessProbe:
#  httpGet:
#    path: /
#    port: http

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  type: RollingUpdate

volumes:
  - name: prometheus-storage
    persistentVolumeClaim:
      claimName: prometheus

volumeMounts:
  - name: prometheus-storage
    mountPath: /prometheus
    subPath: prometheus

env: {}

nodeSelector: {}

tolerations: []

affinity: {}

persistentVolume:
  path: /mnt/metrics
  nodeAffinity:
    hostname:
      - multitest
  storage: 300Mi

storageClass:
  create: true
  name: prometheus
