name: go

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      service:
        required: true
        type: string
      prefix:
        required: true
        type: string
      repository:
        required: true
        type: string

env:
  run_git_url: https://github.com/sku4/ad-run.git
  registry: registry.digitalocean.com/sku4
  repository: repository
  sha: $(echo $GITHUB_SHA | head -c7)
  
jobs:
  go-check:
    uses: sku4/ad-run/.github/workflows/go-check.yml@master
    with:
      repository: ${{ inputs.repository }}

  cd-build:
    runs-on: ubuntu-latest
    needs: go-check

    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          repository: sku4/ad-run

      - name: Build container image
        run: |
          docker compose build --no-cache ${{ inputs.service }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: |
          docker image tag ${{ inputs.image }}:latest ${{ env.registry }}/${{ env.repository }}:${{ inputs.prefix }}-${{ env.sha }}
          docker image push ${{ env.registry }}/${{ env.repository }}:${{ inputs.prefix }}-${{ env.sha }}

  cd-deploy:
    runs-on: ubuntu-latest
    needs: cd-build

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          envs:
            GITHUB_SHA
          script: |
            # Login into Digital Ocean Registry
            docker login -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} -p ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} ${{ env.registry }}

            # Pull containers
            docker pull ${{ env.registry }}/${{ env.repository }}:${{ inputs.prefix }}-${{ env.sha }}
                        
            # Stop running containers
            cd /tmp/ad
            docker compose down --remove-orphans ${{ inputs.service }}
            
            # Download composer
            rm -rf /tmp/ad
            cd /tmp
            git clone ${{ env.run_git_url }} ad
            cd /tmp/ad
            
            # Rename containers
            docker image tag ${{ env.registry }}/${{ env.repository }}:${{ inputs.prefix }}-${{ env.sha }} ${{ inputs.image }}:latest
            
            # Set env variables
            export HOST_URL=${{ secrets.ENV_HOST_URL }}
            export TELEGRAM_BOT_TOKEN=${{ secrets.ENV_TELEGRAM_BOT_TOKEN }}
            export TELEGRAM_FEEDBACK_CHAT_ID=${{ secrets.ENV_TELEGRAM_FEEDBACK_CHAT_ID }}

            # Run docker compose
            docker compose up -d --no-recreate ${{ inputs.service }}

            # Clean unused images
            docker image prune -af
